#!/bin/sh -e

cat <<EOF
export PATH="$(cd $(dirname $0) && pwd)/libexec:${PATH}"
EOF

if [ "$1" = "--aliases" ]
then
    cat <<EOF
alias ddbb="ddb boot"
alias ddbbl="ddb boot --login"
alias ddbh="ddb halt"
alias ddbl="ddb login"
alias ddbq="ddb quick"
EOF
fi
