#!/bin/sh -e

, $(dirname $0)/libexec/common

cat <<EOF
export PATH="$(shreadlink $(dirname $0))/libexec:${PATH}"
EOF

if [ "$1" = "--aliases" ]
then
    cat <<EOF
alias ddbb="ddb boot"
alias ddbbl="ddb boot --login"
alias ddbh="ddb halt"
alias ddbl="ddb login"
EOF
fi
