#!/bin/sh -e
#
# unibuild - Front-end CLI program for Unibuild
#

WHOAMI=$(basename $0)
WHEREAMI=$(dirname $0)

export DDB="$(cd $(dirname $0) && pwd)"

. "${DDB}/common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} COMMAND [ ARGUMENTS ]"

Commands:  (Use 'COMMAND --help' for further help.)"

EOF
    ls "${DDB_COMMANDS}" \
        | grep -F -x -v -e xyzzy \
	| pr -4 -T -t \
	| sed -e 's/^/    /g'
    echo
}


# Handle options

while echo "$1" | grep -E -q -e '^--'
do
    OPTION=$1
    shift

    case "${OPTION}" in
    
	--help|-h|help)
	    help
	    exit 0
	    ;;

	--*)
	    die "Unknown option ${OPTION}.  Use --help for help."
	    ;;
    esac
done

if [ $# -lt 1 ]
then
    help
    exit 0
else
    COMMAND="$1"
    shift
fi


RUN="${DDB_COMMANDS}/${COMMAND}"

[ -x "${RUN}" ] \
    || die "${COMMAND}: Unknown command.  Use --help for help."

exec "${RUN}" "$@"
