#!/bin/sh -e
#
# Start a container
#


. "$(dirname $0)/../common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ] CONTAINER-NAME IMAGE-NAME

Options:
  --login    Log into the container after it has booted.  Implied
               if $LOGIN_ON_BOOT is set to any non-empty value.
  --no-login Don't log into the container after boot.  Overrides
               $LOGIN_ON_BOOT if set.
  --verbose  Print the Docker command used to start the container

Example:  ${WHOAMI} --login thing el9
EOF
}

[ "${DDB_LOGIN_ON_BOOT}" ] \
    && LOGIN_AFTER=true \
	|| LOGIN_AFTER=false

VERBOSE=false
while echo "$1" | grep -E -qe '^--'
do
    case "$1" in
	--help)
	    help
	    exit 0
	    ;;
	
	--login)
	    LOGIN_AFTER=true
	    shift
	    ;;

	--no-login)
	    LOGIN_AFTER=false
	    shift
	    ;;

	--verbose)
	    VERBOSE=true
	    shift
	    ;;

	*)
	    echo "Unknown option $1" 1>&2
	    exit 1
    esac
done

NAME="$1"
CONTAINER_NAME="${DDB_CONTAINER_PREFIX}${NAME}"
# TODO: Check that CONTAINER_NAME exists

# TODO: Check for duplicate container

IMAGE="$2"
IMAGE_FULL="${DDB_CONTAINER_PREFIX}$2"

# TODO: Make this work
#${WHEREAMI}/build --if-new "${BASE}"

USER_ENT=$(getent_passwd $(id -nu))
USER_HOME=$(echo "${USER_ENT}" | cut -d : -f 6)

echo "Starting ${NAME} from image ${IMAGE}"

# Notes:
#
# Docker on macOS uses a Linux VM internally, so the sharing of the
# cgroup volume is portable.
#
# For info on use of the security-opt switch, see
# https://jaosorior.dev/2018/selinux-and-docker-notes.

do_docker()
{
    if ${VERBOSE}
    then
	echo "Starting container ${CONTAINER_NAME}:"
	echo "$@"
    fi

    "$@"
}


case $(uname -s) in
    Darwin)
	PRIVILEGED=--privileged
	;;
    Linux)
	if [ -e /sys/fs/cgroup/cgroup.controllers ]
	then
	    # CGROUPS v2
	    PRIVILEGED=--privileged
	else
	    # CGROUPS v1
	    PRIVILEGED=--privileged
	    VOLUME_CGROUP="--volume /sys/fs/cgroup:/sys/fs/cgroup:ro"
	fi
	;;
    *)
	die "Don't know how to support this OS."
    ;;
esac

# Get image platform architecture
PLATFORM=$(do_docker $DOCKER image inspect \
    "${IMAGE_FULL}" \
    | awk -F \" '/Architecture/ {print $4}' \
)

do_docker $DOCKER run \
    --hostname "${NAME}" \
    --name "${CONTAINER_NAME}" \
    --detach \
    --rm \
    ${PRIVILEGED} \
    ${VOLUME_CGROUP} \
    --volume "${USER_HOME}:${USER_HOME}" \
    --security-opt label:disable \
    --platform "linux/${PLATFORM}" \
    "${IMAGE_FULL}" \
    bash /ddb-entrypoint --user-ent "${USER_ENT}"

if ${LOGIN_AFTER}
then
    # Wait a bit for the container to boot properly
    sleep 2
    echo "Logging into ${NAME}"
    exec "${WHEREAMI}/login" "${NAME}"
fi
