#!/bin/sh -e
#
# Start a container
#


. "$(dirname $0)/../common"

LOGIN_AFTER=false
if [ "$1" = "--login" ]
then
    LOGIN_AFTER=true
    shift
fi

NAME="$1"
CONTAINER_NAME="${DDB_CONTAINER_PREFIX}${NAME}"

# TODO: Check for duplicate container

IMAGE="$2"
IMAGE_FULL="${DDB_CONTAINER_PREFIX}$2"

# TODO: Make this work
#${WHEREAMI}/build --if-new "${BASE}"


# Get the password entry in the standard POSIX format of
# login:password:uid:gid:gecos:homedir:shell

case "$(uname -s)" in
    Darwin)
	# MacOS doesn't have getent, so cook up the equivalent.
	USER_ENT=$(dscacheutil -q user -a name $(id -nu) \
		       | sed -e 's/^[^ ]*: //' \
		       | tr '\n' ':' \
		       | cut -d ':' -f 1,2,3,4,7,5,6)
	;;
    *)
	# Anything else is assumed POSIX
	USER_ENT=$(getent passwd $(id -nu))
esac

USER_HOME=$(echo "${USER_ENT}" | cut -d : -f 6)

echo "Starting ${NAME} as ${IMAGE}"

$DOCKER run \
    --hostname "${NAME}" \
    --name "${CONTAINER_NAME}" \
    --detach \
    --rm \
    --privileged \
    --volume "${USER_HOME}:${USER_HOME}" \
    "${IMAGE_FULL}:latest" \
    bash /ddb-entrypoint --user-ent "${USER_ENT}"

if ${LOGIN_AFTER}
then
    exec "${WHEREAMI}/login" "${NAME}"
fi
