#!/bin/sh -e
#
# Build an image
#
# Usage:  build-container [ OPTIONS ] NAME
#
# Options:
#    --if-new    Build only of the image doesn't exist yet
#

. "$(dirname $0)/../common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} IMAGE-NAME

Example:  ${WHOAMI} el9
EOF
}


if [ "$1" = "--help" ]
then
    help
    exit 0
fi

if [ $# -ne 1 ]
then
    help
    exit 1
fi
NAME="$1"

BASE_IMAGE=$(getkey "${DDB_ETC}/bases" "${NAME}")

CONTAINER_NAME="${DDB_CONTAINER_PREFIX}${NAME}"

cp -r "${DDB}/prep" "${TMPBASE}"

USER_PREP="${HOME}/.ddb/prep.m4"
if [ -r "${USER_PREP}" ]
then
    cp "${USER_PREP}" "${TMPBASE}/prep/prep-steps-user.m4"
fi 

DOCKERFILE="${TMPBASE}/Dockerfile"

cat > "${DOCKERFILE}" <<EOF
FROM ${BASE_IMAGE}
RUN mkdir -p "${DDB_DIR}"
COPY prep "${DDB_DIR}"
RUN "${DDB_DIR}/prep"
EOF

cd "${TMPBASE}"
$DOCKER build --pull -t "${CONTAINER_NAME}" -f "${DOCKERFILE}" .
