#!/bin/sh -e

#
# Stop a container
#

. "$(dirname $0)/../common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ] [ CONTAINER-NAME ... ]

Options:
  --all      Halt all DDB containers

Example:  ${WHOAMI} thing1 thing2
EOF
}


STOP_ALL=false
while echo "$1" | egrep -qe '^--'
do
    case "$1" in
	--help)
	    help
	    exit 0
	    ;;
	
	--all)
	    STOP_ALL=true
	    shift
	    ;;

	*)
	    echo "Unknown option $1" 1>&2
	    exit 1
    esac
done


STOP_LIST="${TMPBASE}/stoplist"
touch "${STOP_LIST}"

if ${STOP_ALL}
then
    $DOCKER container list  --format "{{.Names}}|{{.Names}}\n" --all --filter "name=^${DDB_CONTAINER_PREFIX}" \
	| sed -e "s/^${DDB_CONTAINER_PREFIX}//" \
	      > "${STOP_LIST}"
else
    for ARG in "$@"
    do
	printf "${ARG}|${DDB_CONTAINER_PREFIX}${ARG}\n" >> "${STOP_LIST}"
    done
fi

if [ $(wc -l "${STOP_LIST}" | cut -d ' ' -f 1) -eq 0 -a "${STOP_ALL}" = "false" ]
then
    help
    exit 1
fi   

for STOP in $(cat "${STOP_LIST}")
do
    NAME=$(echo "${STOP}" | cut -d '|' -f 1)
    CONTAINER=$(echo "${STOP}" | cut -d '|' -f 2)

    if ${STOP_ALL}
    then
	printf  "Stopping ${NAME}..."
    fi
    # TODO: Make sure the container exists
    $DOCKER exec -it "${CONTAINER}" "${DDB_DIR}/stop"
    if ${STOP_ALL}
    then
	echo " Done."
    fi


done
