#!/bin/sh -e
#
# Log into a DDB container
#

. "$(dirname $0)/../common"

help()
{
    cat <<EOF
Usage: ${WHOAMI} [ OPTIONS ] CONTAINER-NAME

Options:
  --root     Log in as root instead of $(id -nu)

Example:  ${WHOAMI} --root thing
EOF
}


ROOT=false
while echo "$1" | grep -E -qe '^--'
do
    case "$1" in
	--help)
	    help
	    exit 0
	    ;;
	
	--root)
	    ROOT=true
	    shift
	    ;;
	
	*)
	    echo "Unknown option $1" 1>&2
	    exit 1
    esac
done


if $ROOT
then
    COMMAND=bash
else
    COMMAND="su - $(id -nu)"
fi

CONTAINER_NAME="${DDB_CONTAINER_PREFIX}$1"

exec $DOCKER exec -it "${CONTAINER_NAME}" ${COMMAND}
