#!/bin/sh -e
#
# Start a container
#


. "$(dirname $0)/../common"

NAME="$1"
CONTAINER_NAME="${DDB_CONTAINER_PREFIX}${NAME}"

# TODO: Check for duplicate container

IMAGE="$2"
IMAGE_FULL="${DDB_CONTAINER_PREFIX}$2"
# TODO: Check for presence

USER_ENT=$(getent passwd $(id -nu))
USER_HOME=$(echo "${USER_ENT}" | cut -d : -f 6)

# TODO: Make this work
#${WHEREAMI}/build --if-new "${BASE}"

echo "Starting ${NAME} as ${IMAGE}"

$DOCKER run \
    --hostname "${NAME}" \
    --name "${CONTAINER_NAME}" \
    --detach \
    --rm \
    --privileged \
    --volume "${USER_HOME}:${USER_HOME}" \
    "${IMAGE_FULL}:latest" \
    bash /ddb-entrypoint --user-ent "${USER_ENT}"
